/**
 * #459 — Local Expo config plugin: pin play-services-location version.
 *
 * WHY: react-native-background-geolocation defaults to
 * play-services-location 20.0.0 (ActivityRecognitionClient = CLASS) while
 * expo-location forces 21.0.1 (ActivityRecognitionClient = INTERFACE). Gradle
 * resolves to the highest, so RNBG crashes at runtime with
 * IncompatibleClassChangeError. RNBG reads `playServicesLocationVersion` from
 * rootProject.ext and adapts to the major version, so pinning both libraries
 * to the SAME 21.0.1 fixes the conflict.
 *
 * `android/` is regenerated by `expo prebuild --clean` (and by every EAS
 * build), which wipes any manual edit to android/build.gradle. This plugin
 * re-injects the pin into the generated root build.gradle every time, so the
 * fix is durable — including on EAS cloud builds where we never touch the
 * native project by hand.
 */
const { withProjectBuildGradle } = require('@expo/config-plugins');

const PLAY_SERVICES_LOCATION_VERSION = '21.0.1';
const MARKER = 'playServicesLocationVersion'; // idempotency guard

module.exports = function withPlayServicesLocationPin(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      // Only Groovy build.gradle is supported; skip cleanly otherwise.
      return cfg;
    }
    if (cfg.modResults.contents.includes(MARKER)) {
      // Already pinned (e.g. plugin ran twice) — don't duplicate.
      return cfg;
    }
    const pin = [
      '',
      '// #459 — injected by plugins/withPlayServicesLocationPin.js',
      '// Force one play-services-location version across RNBG + expo-location',
      '// to avoid IncompatibleClassChangeError (ActivityRecognitionClient).',
      'ext {',
      `    playServicesLocationVersion = "${PLAY_SERVICES_LOCATION_VERSION}"`,
      `    googlePlayServicesLocationVersion = "${PLAY_SERVICES_LOCATION_VERSION}"`,
      '}',
      '',
    ].join('\n');
    // Append at the very end so it runs after expo-root-project applies.
    cfg.modResults.contents = cfg.modResults.contents + '\n' + pin;
    return cfg;
  });
};
